name:                polysemy-vinyl
version:             0.1.5.0
git:                 https://gitlab.com/homotopic-tech/polysemy-vinyl
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "dan.firth@homotopic.tech"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Functions for mapping vinyl records in polysemy.
category:            Polysemy Vinyl

description:         Extra functions for using vinyl records in polysemy.

dependencies:
- base >= 4.7 && < 5
- polysemy-extra >= 0.1.6.0 && < 0.3
- polysemy-several >= 0.1 && < 0.2
- polysemy >= 1.3 && < 1.7
- vinyl >= 0.10.0 && < 0.14

library:
  source-dirs: src

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
